// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lap_filter_axis,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.520000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=5,HLS_SYN_FF=336,HLS_SYN_LUT=601}" *)

module lap_filter_axis (
        ap_clk,
        ap_rst_n,
        lap_fil_enable_V,
        ins_TDATA,
        ins_TVALID,
        ins_TREADY,
        ins_TKEEP,
        ins_TSTRB,
        ins_TUSER,
        ins_TLAST,
        ins_TID,
        ins_TDEST,
        outs_TDATA,
        outs_TVALID,
        outs_TREADY,
        outs_TKEEP,
        outs_TSTRB,
        outs_TUSER,
        outs_TLAST,
        outs_TID,
        outs_TDEST,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st10_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv20_0 = 20'b00000000000000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv20_E1000 = 20'b11100001000000000000;
parameter    ap_const_lv20_1 = 20'b1;
parameter    ap_const_lv11_500 = 11'b10100000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv11_4FF = 11'b10011111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv16_96 = 16'b10010110;
parameter    ap_const_lv14_1D = 14'b11101;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv16_4D = 16'b1001101;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv32_10101 = 32'b10000000100000001;
parameter    ap_const_lv32_FFFFFF = 32'b111111111111111111111111;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input  [0:0] lap_fil_enable_V;
input  [31:0] ins_TDATA;
input   ins_TVALID;
output   ins_TREADY;
input  [3:0] ins_TKEEP;
input  [3:0] ins_TSTRB;
input  [0:0] ins_TUSER;
input  [0:0] ins_TLAST;
input  [0:0] ins_TID;
input  [0:0] ins_TDEST;
output  [31:0] outs_TDATA;
output   outs_TVALID;
input   outs_TREADY;
output  [3:0] outs_TKEEP;
output  [3:0] outs_TSTRB;
output  [0:0] outs_TUSER;
output  [0:0] outs_TLAST;
output  [0:0] outs_TID;
output  [0:0] outs_TDEST;
output  [31:0] ap_return;

reg ins_TREADY;
reg[31:0] outs_TDATA;
reg outs_TVALID;
reg[3:0] outs_TKEEP;
reg[3:0] outs_TSTRB;
reg[0:0] outs_TUSER;
reg[0:0] outs_TLAST;
reg[0:0] outs_TID;
reg[0:0] outs_TDEST;
reg    ap_rst_n_inv;
reg   [19:0] indvar_flatten_reg_292;
reg   [9:0] y_reg_303;
reg   [10:0] x_reg_314;
wire   [0:0] lap_fil_enable_V_read_read_fu_210_p2;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_47;
wire   [0:0] grp_fu_338_p1;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_57;
wire   [0:0] exitcond_flatten_fu_389_p2;
reg   [0:0] exitcond_flatten_reg_925;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_69;
wire   [0:0] lap_user_V_fu_471_p2;
reg    ap_sig_bdd_77;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_ioackin_outs_TREADY;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it2;
wire   [19:0] indvar_flatten_next_fu_395_p2;
wire   [9:0] y_mid2_fu_421_p3;
reg   [9:0] y_mid2_reg_934;
reg   [0:0] lap_user_V_reg_939;
reg   [0:0] ap_reg_ppstg_lap_user_V_reg_939_pp0_it1;
reg   [0:0] ap_reg_ppstg_lap_user_V_reg_939_pp0_it2;
reg   [0:0] ap_reg_ppstg_lap_user_V_reg_939_pp0_it3;
reg   [0:0] ap_reg_ppstg_lap_user_V_reg_939_pp0_it4;
reg   [0:0] ap_reg_ppstg_lap_user_V_reg_939_pp0_it5;
reg   [10:0] line_buf_0_addr_reg_944;
reg   [10:0] line_buf_1_addr_reg_950;
reg   [10:0] ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it1;
reg   [10:0] ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it2;
reg   [10:0] ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it3;
wire   [0:0] or_cond_13_fu_504_p2;
reg   [0:0] or_cond_13_reg_956;
reg   [0:0] ap_reg_ppstg_or_cond_13_reg_956_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond_13_reg_956_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond_13_reg_956_pp0_it3;
wire   [0:0] lap_last_V_fu_510_p2;
reg   [0:0] lap_last_V_reg_961;
reg   [0:0] ap_reg_ppstg_lap_last_V_reg_961_pp0_it1;
reg   [0:0] ap_reg_ppstg_lap_last_V_reg_961_pp0_it2;
reg   [0:0] ap_reg_ppstg_lap_last_V_reg_961_pp0_it3;
reg   [0:0] ap_reg_ppstg_lap_last_V_reg_961_pp0_it4;
reg   [0:0] ap_reg_ppstg_lap_last_V_reg_961_pp0_it5;
wire   [10:0] x_1_fu_516_p2;
wire   [7:0] b_fu_526_p1;
reg   [7:0] b_reg_971;
wire   [7:0] line_buf_0_q0;
reg   [7:0] line_buf_0_load_reg_976;
wire   [7:0] line_buf_1_q0;
reg   [7:0] line_buf_1_load_reg_982;
reg   [7:0] ap_reg_ppstg_line_buf_1_load_reg_982_pp0_it2;
reg   [7:0] r_reg_988;
reg   [7:0] ap_reg_ppstg_r_reg_988_pp0_it2;
wire   [15:0] tmp_3_i_fu_554_p2;
reg   [15:0] tmp_3_i_reg_993;
wire   [15:0] tmp1_fu_643_p2;
reg   [15:0] tmp1_reg_998;
wire   [31:0] sum3_neg_i_fu_690_p2;
reg   [31:0] sum3_neg_i_reg_1003;
reg   [7:0] pix_mat_2_1_1_reg_1008;
wire   [31:0] tmp_7_i_fu_763_p2;
reg   [31:0] tmp_7_i_reg_1014;
wire  signed [31:0] y_1_fu_777_p2;
wire   [0:0] icmp_fu_800_p2;
reg   [0:0] icmp_reg_1024;
reg   [0:0] ap_reg_ppstg_icmp_reg_1024_pp0_it5;
wire   [0:0] or_cond_fu_812_p2;
reg   [0:0] or_cond_reg_1029;
reg   [0:0] ap_reg_ppstg_or_cond_reg_1029_pp0_it5;
wire   [10:0] line_buf_0_address0;
reg    line_buf_0_ce0;
wire   [10:0] line_buf_0_address1;
reg    line_buf_0_ce1;
reg    line_buf_0_we1;
wire   [7:0] line_buf_0_d1;
wire   [7:0] line_buf_0_q1;
wire   [10:0] line_buf_1_address0;
reg    line_buf_1_ce0;
wire   [10:0] line_buf_1_address1;
reg    line_buf_1_ce1;
reg    line_buf_1_we1;
wire   [7:0] line_buf_1_d1;
wire   [7:0] line_buf_1_q1;
reg   [9:0] y_phi_fu_307_p4;
wire   [63:0] tmp_5_fu_482_p1;
reg   [7:0] pix_mat_2_1_fu_158;
reg   [23:0] pix_mat_0_0_fu_162;
reg   [23:0] pix_mat_0_1_fu_166;
wire   [23:0] pix_mat_0_1_1_fu_621_p1;
reg   [7:0] pix_mat_2_0_fu_170;
reg   [23:0] pix_mat_1_0_fu_174;
reg   [23:0] pix_mat_1_1_fu_178;
wire   [23:0] pix_mat_1_1_1_fu_627_p1;
reg   [0:0] tmp_user_V_2_fu_182;
reg   [31:0] tmp_data_V_3_fu_186;
reg   [3:0] tmp_keep_V_3_fu_190;
reg   [3:0] tmp_strb_V_3_fu_194;
reg   [0:0] tmp_last_V_4_fu_198;
reg   [0:0] tmp_id_V_3_fu_202;
reg   [0:0] tmp_dest_V_3_fu_206;
wire   [31:0] tmp_data_V_4_fu_828_p3;
reg    ap_reg_ioackin_outs_TREADY = 1'b0;
wire   [0:0] exitcond_fu_401_p2;
wire   [9:0] y_s_fu_415_p2;
wire   [8:0] tmp_fu_429_p4;
wire   [10:0] x_mid2_fu_407_p3;
wire   [9:0] tmp_3_fu_445_p1;
wire   [0:0] tmp_6_fu_455_p3;
wire   [9:0] tmp_4_fu_449_p2;
wire   [10:0] tmp_2_fu_463_p3;
wire   [9:0] tmp_12_fu_488_p4;
wire   [0:0] icmp2_fu_498_p2;
wire   [0:0] icmp1_fu_439_p2;
wire   [7:0] g_fu_530_p4;
wire   [7:0] tmp_3_i_fu_554_p0;
wire   [7:0] tmp_4_i_fu_633_p0;
wire   [13:0] tmp_4_i_fu_633_p2;
wire   [15:0] tmp_4_i_cast_fu_639_p1;
wire   [26:0] tmp_9_fu_648_p3;
wire   [24:0] pix_mat_0_1_cast_fu_600_p1;
wire   [24:0] pix_mat_0_0_cast_fu_604_p1;
wire   [24:0] tmp2_fu_660_p2;
wire   [24:0] pix_mat_0_2_cast6_fu_624_p1;
wire   [24:0] pix_mat_1_0_cast_fu_596_p1;
wire   [24:0] tmp3_fu_670_p2;
wire   [25:0] tmp3_cast_fu_676_p1;
wire   [25:0] tmp2_cast_fu_666_p1;
wire   [25:0] sum2_i_fu_680_p2;
wire   [31:0] tmp_i1_fu_656_p1;
wire   [31:0] sum2_i_cast_fu_686_p1;
wire   [7:0] tmp_2_i_fu_731_p0;
wire   [15:0] tmp_2_i_fu_731_p2;
wire   [15:0] y_f_fu_737_p2;
wire   [31:0] pix_mat_1_2_fu_725_p1;
wire   [31:0] tmp_i1_12_fu_752_p2;
wire   [31:0] pix_mat_2_0_cast_fu_712_p1;
wire   [31:0] tmp_6_i_fu_757_p2;
wire   [31:0] pix_mat_2_1_cast_fu_716_p1;
wire   [31:0] y_4_cast_fu_774_p1;
wire   [23:0] tmp_11_fu_790_p4;
wire  signed [31:0] grp_fu_806_p0;
wire   [17:0] grp_fu_806_p1;
wire   [0:0] tmp_10_fu_782_p3;
wire   [0:0] tmp_8_fu_824_p2;
wire   [31:0] newSel4_cast_fu_817_p3;
wire  signed [31:0] grp_fu_806_p2;
reg    grp_fu_806_ce;
reg    ap_sig_cseq_ST_st10_fsm_3;
reg    ap_sig_bdd_646;
reg   [3:0] ap_NS_fsm;
wire   [15:0] tmp_2_i_fu_731_p00;
wire   [15:0] tmp_3_i_fu_554_p00;
wire   [13:0] tmp_4_i_fu_633_p00;
reg    ap_sig_bdd_265;
reg    ap_sig_bdd_681;


lap_filter_axis_line_buf_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
line_buf_0_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( line_buf_0_address0 ),
    .ce0( line_buf_0_ce0 ),
    .q0( line_buf_0_q0 ),
    .address1( line_buf_0_address1 ),
    .ce1( line_buf_0_ce1 ),
    .we1( line_buf_0_we1 ),
    .d1( line_buf_0_d1 ),
    .q1( line_buf_0_q1 )
);

lap_filter_axis_line_buf_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
line_buf_1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( line_buf_1_address0 ),
    .ce0( line_buf_1_ce0 ),
    .q0( line_buf_1_q0 ),
    .address1( line_buf_1_address1 ),
    .ce1( line_buf_1_ce1 ),
    .we1( line_buf_1_we1 ),
    .d1( line_buf_1_d1 ),
    .q1( line_buf_1_q1 )
);

lap_filter_axis_mul_32s_18ns_32_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 32 ))
lap_filter_axis_mul_32s_18ns_32_3_U0(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_806_p0 ),
    .din1( grp_fu_806_p1 ),
    .ce( grp_fu_806_ce ),
    .dout( grp_fu_806_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_outs_TREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_outs_TREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_outs_TREADY <= ap_const_logic_0;
    end else begin
        if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) | (~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
            ap_reg_ioackin_outs_TREADY <= ap_const_logic_0;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) & (ap_const_logic_1 == outs_TREADY)) | (~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) & (ap_const_logic_1 == outs_TREADY)))) begin
            ap_reg_ioackin_outs_TREADY <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(exitcond_flatten_fu_389_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
        indvar_flatten_reg_292 <= ap_const_lv20_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        indvar_flatten_reg_292 <= indvar_flatten_next_fu_395_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == lap_user_V_fu_471_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        tmp_user_V_2_fu_182 <= ins_TUSER;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
        tmp_user_V_2_fu_182 <= ap_const_lv1_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
        x_reg_314 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        x_reg_314 <= x_1_fu_516_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
        y_reg_303 <= ap_const_lv10_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        y_reg_303 <= y_mid2_reg_934;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it1 <= exitcond_flatten_reg_925;
        ap_reg_ppstg_lap_last_V_reg_961_pp0_it1 <= lap_last_V_reg_961;
        ap_reg_ppstg_lap_user_V_reg_939_pp0_it1 <= lap_user_V_reg_939;
        ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it1 <= line_buf_1_addr_reg_950;
        ap_reg_ppstg_or_cond_13_reg_956_pp0_it1 <= or_cond_13_reg_956;
        exitcond_flatten_reg_925 <= exitcond_flatten_fu_389_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
        ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it2 <= ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it1;
        ap_reg_ppstg_icmp_reg_1024_pp0_it5 <= icmp_reg_1024;
        ap_reg_ppstg_lap_last_V_reg_961_pp0_it2 <= ap_reg_ppstg_lap_last_V_reg_961_pp0_it1;
        ap_reg_ppstg_lap_last_V_reg_961_pp0_it3 <= ap_reg_ppstg_lap_last_V_reg_961_pp0_it2;
        ap_reg_ppstg_lap_last_V_reg_961_pp0_it4 <= ap_reg_ppstg_lap_last_V_reg_961_pp0_it3;
        ap_reg_ppstg_lap_last_V_reg_961_pp0_it5 <= ap_reg_ppstg_lap_last_V_reg_961_pp0_it4;
        ap_reg_ppstg_lap_user_V_reg_939_pp0_it2 <= ap_reg_ppstg_lap_user_V_reg_939_pp0_it1;
        ap_reg_ppstg_lap_user_V_reg_939_pp0_it3 <= ap_reg_ppstg_lap_user_V_reg_939_pp0_it2;
        ap_reg_ppstg_lap_user_V_reg_939_pp0_it4 <= ap_reg_ppstg_lap_user_V_reg_939_pp0_it3;
        ap_reg_ppstg_lap_user_V_reg_939_pp0_it5 <= ap_reg_ppstg_lap_user_V_reg_939_pp0_it4;
        ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it2 <= ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it1;
        ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it3 <= ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it2;
        ap_reg_ppstg_line_buf_1_load_reg_982_pp0_it2 <= line_buf_1_load_reg_982;
        ap_reg_ppstg_or_cond_13_reg_956_pp0_it2 <= ap_reg_ppstg_or_cond_13_reg_956_pp0_it1;
        ap_reg_ppstg_or_cond_13_reg_956_pp0_it3 <= ap_reg_ppstg_or_cond_13_reg_956_pp0_it2;
        ap_reg_ppstg_or_cond_reg_1029_pp0_it5 <= or_cond_reg_1029;
        ap_reg_ppstg_r_reg_988_pp0_it2 <= r_reg_988;
        icmp_reg_1024 <= icmp_fu_800_p2;
        or_cond_reg_1029 <= or_cond_fu_812_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        b_reg_971 <= b_fu_526_p1;
        line_buf_0_load_reg_976 <= line_buf_0_q0;
        line_buf_1_load_reg_982 <= line_buf_1_q0;
        r_reg_988 <= {{tmp_data_V_3_fu_186[ap_const_lv32_17 : ap_const_lv32_10]}};
        tmp_3_i_reg_993[1] <= tmp_3_i_fu_554_p2[1];
tmp_3_i_reg_993[2] <= tmp_3_i_fu_554_p2[2];
tmp_3_i_reg_993[3] <= tmp_3_i_fu_554_p2[3];
tmp_3_i_reg_993[4] <= tmp_3_i_fu_554_p2[4];
tmp_3_i_reg_993[5] <= tmp_3_i_fu_554_p2[5];
tmp_3_i_reg_993[6] <= tmp_3_i_fu_554_p2[6];
tmp_3_i_reg_993[7] <= tmp_3_i_fu_554_p2[7];
tmp_3_i_reg_993[8] <= tmp_3_i_fu_554_p2[8];
tmp_3_i_reg_993[9] <= tmp_3_i_fu_554_p2[9];
tmp_3_i_reg_993[10] <= tmp_3_i_fu_554_p2[10];
tmp_3_i_reg_993[11] <= tmp_3_i_fu_554_p2[11];
tmp_3_i_reg_993[12] <= tmp_3_i_fu_554_p2[12];
tmp_3_i_reg_993[13] <= tmp_3_i_fu_554_p2[13];
tmp_3_i_reg_993[14] <= tmp_3_i_fu_554_p2[14];
tmp_3_i_reg_993[15] <= tmp_3_i_fu_554_p2[15];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        lap_last_V_reg_961 <= lap_last_V_fu_510_p2;
        lap_user_V_reg_939 <= lap_user_V_fu_471_p2;
        line_buf_0_addr_reg_944 <= tmp_5_fu_482_p1;
        line_buf_1_addr_reg_950 <= tmp_5_fu_482_p1;
        or_cond_13_reg_956 <= or_cond_13_fu_504_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        pix_mat_0_0_fu_162[0] <= pix_mat_0_1_fu_166[0];
pix_mat_0_0_fu_162[1] <= pix_mat_0_1_fu_166[1];
pix_mat_0_0_fu_162[2] <= pix_mat_0_1_fu_166[2];
pix_mat_0_0_fu_162[3] <= pix_mat_0_1_fu_166[3];
pix_mat_0_0_fu_162[4] <= pix_mat_0_1_fu_166[4];
pix_mat_0_0_fu_162[5] <= pix_mat_0_1_fu_166[5];
pix_mat_0_0_fu_162[6] <= pix_mat_0_1_fu_166[6];
pix_mat_0_0_fu_162[7] <= pix_mat_0_1_fu_166[7];
        pix_mat_1_0_fu_174[0] <= pix_mat_1_1_fu_178[0];
pix_mat_1_0_fu_174[1] <= pix_mat_1_1_fu_178[1];
pix_mat_1_0_fu_174[2] <= pix_mat_1_1_fu_178[2];
pix_mat_1_0_fu_174[3] <= pix_mat_1_1_fu_178[3];
pix_mat_1_0_fu_174[4] <= pix_mat_1_1_fu_178[4];
pix_mat_1_0_fu_174[5] <= pix_mat_1_1_fu_178[5];
pix_mat_1_0_fu_174[6] <= pix_mat_1_1_fu_178[6];
pix_mat_1_0_fu_174[7] <= pix_mat_1_1_fu_178[7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it1))) begin
        pix_mat_0_1_fu_166[0] <= pix_mat_0_1_1_fu_621_p1[0];
pix_mat_0_1_fu_166[1] <= pix_mat_0_1_1_fu_621_p1[1];
pix_mat_0_1_fu_166[2] <= pix_mat_0_1_1_fu_621_p1[2];
pix_mat_0_1_fu_166[3] <= pix_mat_0_1_1_fu_621_p1[3];
pix_mat_0_1_fu_166[4] <= pix_mat_0_1_1_fu_621_p1[4];
pix_mat_0_1_fu_166[5] <= pix_mat_0_1_1_fu_621_p1[5];
pix_mat_0_1_fu_166[6] <= pix_mat_0_1_1_fu_621_p1[6];
pix_mat_0_1_fu_166[7] <= pix_mat_0_1_1_fu_621_p1[7];
        pix_mat_1_1_fu_178[0] <= pix_mat_1_1_1_fu_627_p1[0];
pix_mat_1_1_fu_178[1] <= pix_mat_1_1_1_fu_627_p1[1];
pix_mat_1_1_fu_178[2] <= pix_mat_1_1_1_fu_627_p1[2];
pix_mat_1_1_fu_178[3] <= pix_mat_1_1_1_fu_627_p1[3];
pix_mat_1_1_fu_178[4] <= pix_mat_1_1_1_fu_627_p1[4];
pix_mat_1_1_fu_178[5] <= pix_mat_1_1_1_fu_627_p1[5];
pix_mat_1_1_fu_178[6] <= pix_mat_1_1_1_fu_627_p1[6];
pix_mat_1_1_fu_178[7] <= pix_mat_1_1_1_fu_627_p1[7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        pix_mat_2_0_fu_170 <= pix_mat_2_1_fu_158;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it2))) begin
        pix_mat_2_1_1_reg_1008 <= {{y_f_fu_737_p2[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_7_i_reg_1014 <= tmp_7_i_fu_763_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it2))) begin
        pix_mat_2_1_fu_158 <= {{y_f_fu_737_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_925_pp0_it1))) begin
        sum3_neg_i_reg_1003 <= sum3_neg_i_fu_690_p2;
        tmp1_reg_998 <= tmp1_fu_643_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == lap_user_V_fu_471_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
        tmp_data_V_3_fu_186 <= ins_TDATA;
        tmp_dest_V_3_fu_206 <= ins_TDEST;
        tmp_id_V_3_fu_202 <= ins_TID;
        tmp_keep_V_3_fu_190 <= ins_TKEEP;
        tmp_last_V_4_fu_198 <= ins_TLAST;
        tmp_strb_V_3_fu_194 <= ins_TSTRB;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        y_mid2_reg_934 <= y_mid2_fu_421_p3;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_69)
begin
    if (ap_sig_bdd_69) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_3 assign process. ///
always @ (ap_sig_bdd_646)
begin
    if (ap_sig_bdd_646) begin
        ap_sig_cseq_ST_st10_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_47)
begin
    if (ap_sig_bdd_47) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_57)
begin
    if (ap_sig_bdd_57) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_outs_TREADY assign process. ///
always @ (outs_TREADY or ap_reg_ioackin_outs_TREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_outs_TREADY)) begin
        ap_sig_ioackin_outs_TREADY = outs_TREADY;
    end else begin
        ap_sig_ioackin_outs_TREADY = ap_const_logic_1;
    end
end

/// grp_fu_806_ce assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        grp_fu_806_ce = ap_const_logic_1;
    end else begin
        grp_fu_806_ce = ap_const_logic_0;
    end
end

/// ins_TREADY assign process. ///
always @ (ins_TVALID or lap_fil_enable_V_read_read_fu_210_p2 or ap_sig_cseq_ST_st2_fsm_1 or exitcond_flatten_fu_389_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or lap_user_V_fu_471_p2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ins_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == lap_user_V_fu_471_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))))) begin
        ins_TREADY = ap_const_logic_1;
    end else begin
        ins_TREADY = ap_const_logic_0;
    end
end

/// line_buf_0_ce0 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_0_ce0 = ap_const_logic_1;
    end else begin
        line_buf_0_ce0 = ap_const_logic_0;
    end
end

/// line_buf_0_ce1 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_0_ce1 = ap_const_logic_1;
    end else begin
        line_buf_0_ce1 = ap_const_logic_0;
    end
end

/// line_buf_0_we1 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_0_we1 = ap_const_logic_1;
    end else begin
        line_buf_0_we1 = ap_const_logic_0;
    end
end

/// line_buf_1_ce0 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_1_ce0 = ap_const_logic_1;
    end else begin
        line_buf_1_ce0 = ap_const_logic_0;
    end
end

/// line_buf_1_ce1 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_1_ce1 = ap_const_logic_1;
    end else begin
        line_buf_1_ce1 = ap_const_logic_0;
    end
end

/// line_buf_1_we1 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        line_buf_1_we1 = ap_const_logic_1;
    end else begin
        line_buf_1_we1 = ap_const_logic_0;
    end
end

/// outs_TDATA assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or tmp_data_V_3_fu_186 or tmp_data_V_4_fu_828_p3 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TDATA = tmp_data_V_4_fu_828_p3;
        end else if (ap_sig_bdd_265) begin
            outs_TDATA = tmp_data_V_3_fu_186;
        end else begin
            outs_TDATA = 'bx;
        end
    end else begin
        outs_TDATA = 'bx;
    end
end

/// outs_TDEST assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or tmp_dest_V_3_fu_206 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TDEST = ap_const_lv1_0;
        end else if (ap_sig_bdd_265) begin
            outs_TDEST = tmp_dest_V_3_fu_206;
        end else begin
            outs_TDEST = 'bx;
        end
    end else begin
        outs_TDEST = 'bx;
    end
end

/// outs_TID assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or tmp_id_V_3_fu_202 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TID = ap_const_lv1_0;
        end else if (ap_sig_bdd_265) begin
            outs_TID = tmp_id_V_3_fu_202;
        end else begin
            outs_TID = 'bx;
        end
    end else begin
        outs_TID = 'bx;
    end
end

/// outs_TKEEP assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or tmp_keep_V_3_fu_190 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TKEEP = ap_const_lv4_0;
        end else if (ap_sig_bdd_265) begin
            outs_TKEEP = tmp_keep_V_3_fu_190;
        end else begin
            outs_TKEEP = 'bx;
        end
    end else begin
        outs_TKEEP = 'bx;
    end
end

/// outs_TLAST assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_reg_ppstg_lap_last_V_reg_961_pp0_it5 or tmp_last_V_4_fu_198 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TLAST = ap_reg_ppstg_lap_last_V_reg_961_pp0_it5;
        end else if (ap_sig_bdd_265) begin
            outs_TLAST = tmp_last_V_4_fu_198;
        end else begin
            outs_TLAST = 'bx;
        end
    end else begin
        outs_TLAST = 'bx;
    end
end

/// outs_TSTRB assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or tmp_strb_V_3_fu_194 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TSTRB = ap_const_lv4_0;
        end else if (ap_sig_bdd_265) begin
            outs_TSTRB = tmp_strb_V_3_fu_194;
        end else begin
            outs_TSTRB = 'bx;
        end
    end else begin
        outs_TSTRB = 'bx;
    end
end

/// outs_TUSER assign process. ///
always @ (ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_reg_ppstg_lap_user_V_reg_939_pp0_it5 or tmp_user_V_2_fu_182 or ap_sig_bdd_265 or ap_sig_bdd_681)
begin
    if (~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        if (ap_sig_bdd_681) begin
            outs_TUSER = ap_reg_ppstg_lap_user_V_reg_939_pp0_it5;
        end else if (ap_sig_bdd_265) begin
            outs_TUSER = tmp_user_V_2_fu_182;
        end else begin
            outs_TUSER = 'bx;
        end
    end else begin
        outs_TUSER = 'bx;
    end
end

/// outs_TVALID assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6 or ap_reg_ioackin_outs_TREADY)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) & (ap_const_logic_0 == ap_reg_ioackin_outs_TREADY)) | (~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~(ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) & (ap_const_logic_0 == ap_reg_ioackin_outs_TREADY)))) begin
        outs_TVALID = ap_const_logic_1;
    end else begin
        outs_TVALID = ap_const_logic_0;
    end
end

/// y_phi_fu_307_p4 assign process. ///
always @ (y_reg_303 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or y_mid2_reg_934)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        y_phi_fu_307_p4 = y_mid2_reg_934;
    end else begin
        y_phi_fu_307_p4 = y_reg_303;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ins_TVALID or lap_fil_enable_V_read_read_fu_210_p2 or ap_CS_fsm or grp_fu_338_p1 or exitcond_flatten_reg_925 or ap_sig_bdd_77 or ap_reg_ppiten_pp0_it0 or ap_sig_ioackin_outs_TREADY or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it6)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(ins_TVALID == ap_const_logic_0) & ~(grp_fu_338_p1 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((~(ins_TVALID == ap_const_logic_0) & (grp_fu_338_p1 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_77 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_0 == ap_sig_ioackin_outs_TREADY) & ~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_st10_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st10_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return = ap_const_lv32_0;

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_265 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or exitcond_flatten_reg_925 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1)
begin
    ap_sig_bdd_265 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_flatten_reg_925 == ap_const_lv1_0) & (lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1));
end

/// ap_sig_bdd_47 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_47 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_57 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_57 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_646 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_646 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_681 assign process. ///
always @ (lap_fil_enable_V_read_read_fu_210_p2 or ap_reg_ppiten_pp0_it6)
begin
    ap_sig_bdd_681 = (~(lap_fil_enable_V_read_read_fu_210_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6));
end

/// ap_sig_bdd_69 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_69 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_77 assign process. ///
always @ (ins_TVALID or exitcond_flatten_fu_389_p2 or lap_user_V_fu_471_p2)
begin
    ap_sig_bdd_77 = ((ins_TVALID == ap_const_logic_0) & (exitcond_flatten_fu_389_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == lap_user_V_fu_471_p2));
end
assign b_fu_526_p1 = tmp_data_V_3_fu_186[7:0];
assign exitcond_flatten_fu_389_p2 = (indvar_flatten_reg_292 == ap_const_lv20_E1000? 1'b1: 1'b0);
assign exitcond_fu_401_p2 = (x_reg_314 == ap_const_lv11_500? 1'b1: 1'b0);
assign g_fu_530_p4 = {{tmp_data_V_3_fu_186[ap_const_lv32_F : ap_const_lv32_8]}};
assign grp_fu_338_p1 = ins_TUSER;
assign grp_fu_806_p0 = y_1_fu_777_p2;
assign grp_fu_806_p1 = ap_const_lv32_10101;
assign icmp1_fu_439_p2 = (tmp_fu_429_p4 == ap_const_lv9_0? 1'b1: 1'b0);
assign icmp2_fu_498_p2 = (tmp_12_fu_488_p4 == ap_const_lv10_0? 1'b1: 1'b0);
assign icmp_fu_800_p2 = ($signed(tmp_11_fu_790_p4) > $signed(24'b000000000000000000000000)? 1'b1: 1'b0);
assign indvar_flatten_next_fu_395_p2 = (indvar_flatten_reg_292 + ap_const_lv20_1);
assign lap_fil_enable_V_read_read_fu_210_p2 = lap_fil_enable_V;
assign lap_last_V_fu_510_p2 = (x_mid2_fu_407_p3 == ap_const_lv11_4FF? 1'b1: 1'b0);
assign lap_user_V_fu_471_p2 = (tmp_2_fu_463_p3 == ap_const_lv11_0? 1'b1: 1'b0);
assign line_buf_0_address0 = tmp_5_fu_482_p1;
assign line_buf_0_address1 = line_buf_0_addr_reg_944;
assign line_buf_0_d1 = line_buf_1_q0;
assign line_buf_1_address0 = tmp_5_fu_482_p1;
assign line_buf_1_address1 = ap_reg_ppstg_line_buf_1_addr_reg_950_pp0_it3;
assign line_buf_1_d1 = pix_mat_2_1_1_reg_1008;
assign newSel4_cast_fu_817_p3 = ((ap_reg_ppstg_or_cond_reg_1029_pp0_it5)? ap_const_lv32_0: ap_const_lv32_FFFFFF);
assign or_cond_13_fu_504_p2 = (icmp2_fu_498_p2 | icmp1_fu_439_p2);
assign or_cond_fu_812_p2 = (ap_reg_ppstg_or_cond_13_reg_956_pp0_it3 | tmp_10_fu_782_p3);
assign pix_mat_0_0_cast_fu_604_p1 = pix_mat_0_0_fu_162;
assign pix_mat_0_1_1_fu_621_p1 = line_buf_0_load_reg_976;
assign pix_mat_0_1_cast_fu_600_p1 = pix_mat_0_1_fu_166;
assign pix_mat_0_2_cast6_fu_624_p1 = line_buf_0_load_reg_976;
assign pix_mat_1_0_cast_fu_596_p1 = pix_mat_1_0_fu_174;
assign pix_mat_1_1_1_fu_627_p1 = line_buf_1_load_reg_982;
assign pix_mat_1_2_fu_725_p1 = ap_reg_ppstg_line_buf_1_load_reg_982_pp0_it2;
assign pix_mat_2_0_cast_fu_712_p1 = pix_mat_2_0_fu_170;
assign pix_mat_2_1_cast_fu_716_p1 = pix_mat_2_1_fu_158;
assign sum2_i_cast_fu_686_p1 = sum2_i_fu_680_p2;
assign sum2_i_fu_680_p2 = (tmp3_cast_fu_676_p1 + tmp2_cast_fu_666_p1);
assign sum3_neg_i_fu_690_p2 = (tmp_i1_fu_656_p1 - sum2_i_cast_fu_686_p1);
assign tmp1_fu_643_p2 = (tmp_4_i_cast_fu_639_p1 + tmp_3_i_reg_993);
assign tmp2_cast_fu_666_p1 = tmp2_fu_660_p2;
assign tmp2_fu_660_p2 = (pix_mat_0_1_cast_fu_600_p1 + pix_mat_0_0_cast_fu_604_p1);
assign tmp3_cast_fu_676_p1 = tmp3_fu_670_p2;
assign tmp3_fu_670_p2 = (pix_mat_0_2_cast6_fu_624_p1 + pix_mat_1_0_cast_fu_596_p1);
assign tmp_10_fu_782_p3 = y_1_fu_777_p2[ap_const_lv32_1F];
assign tmp_11_fu_790_p4 = {{y_1_fu_777_p2[ap_const_lv32_1F : ap_const_lv32_8]}};
assign tmp_12_fu_488_p4 = {{x_mid2_fu_407_p3[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_2_fu_463_p3 = {{tmp_6_fu_455_p3}, {tmp_4_fu_449_p2}};
assign tmp_2_i_fu_731_p0 = tmp_2_i_fu_731_p00;
assign tmp_2_i_fu_731_p00 = ap_reg_ppstg_r_reg_988_pp0_it2;
assign tmp_2_i_fu_731_p2 = (tmp_2_i_fu_731_p0 * $signed('h4D));
assign tmp_3_fu_445_p1 = x_mid2_fu_407_p3[9:0];
assign tmp_3_i_fu_554_p0 = tmp_3_i_fu_554_p00;
assign tmp_3_i_fu_554_p00 = g_fu_530_p4;
assign tmp_3_i_fu_554_p2 = (tmp_3_i_fu_554_p0 * $signed('h96));
assign tmp_4_fu_449_p2 = (tmp_3_fu_445_p1 | y_mid2_fu_421_p3);
assign tmp_4_i_cast_fu_639_p1 = tmp_4_i_fu_633_p2;
assign tmp_4_i_fu_633_p0 = tmp_4_i_fu_633_p00;
assign tmp_4_i_fu_633_p00 = b_reg_971;
assign tmp_4_i_fu_633_p2 = (tmp_4_i_fu_633_p0 * $signed('h1D));
assign tmp_5_fu_482_p1 = x_mid2_fu_407_p3;
assign tmp_6_fu_455_p3 = x_mid2_fu_407_p3[ap_const_lv32_A];
assign tmp_6_i_fu_757_p2 = (tmp_i1_12_fu_752_p2 - pix_mat_2_0_cast_fu_712_p1);
assign tmp_7_i_fu_763_p2 = (tmp_6_i_fu_757_p2 - pix_mat_2_1_cast_fu_716_p1);
assign tmp_8_fu_824_p2 = (ap_reg_ppstg_or_cond_reg_1029_pp0_it5 | ap_reg_ppstg_icmp_reg_1024_pp0_it5);
assign tmp_9_fu_648_p3 = {{pix_mat_1_1_fu_178}, {ap_const_lv3_0}};
assign tmp_data_V_4_fu_828_p3 = ((tmp_8_fu_824_p2)? newSel4_cast_fu_817_p3: grp_fu_806_p2);
assign tmp_fu_429_p4 = {{y_mid2_fu_421_p3[ap_const_lv32_9 : ap_const_lv32_1]}};
assign tmp_i1_12_fu_752_p2 = (sum3_neg_i_reg_1003 - pix_mat_1_2_fu_725_p1);
assign tmp_i1_fu_656_p1 = tmp_9_fu_648_p3;
assign x_1_fu_516_p2 = (x_mid2_fu_407_p3 + ap_const_lv11_1);
assign x_mid2_fu_407_p3 = ((exitcond_fu_401_p2)? ap_const_lv11_0: x_reg_314);
assign y_1_fu_777_p2 = (tmp_7_i_reg_1014 - y_4_cast_fu_774_p1);
assign y_4_cast_fu_774_p1 = pix_mat_2_1_1_reg_1008;
assign y_f_fu_737_p2 = (tmp1_reg_998 + tmp_2_i_fu_731_p2);
assign y_mid2_fu_421_p3 = ((exitcond_fu_401_p2)? y_s_fu_415_p2: y_phi_fu_307_p4);
assign y_s_fu_415_p2 = (y_phi_fu_307_p4 + ap_const_lv10_1);
always @ (posedge ap_clk)
begin
    tmp_3_i_reg_993[0] <= 1'b0;
    pix_mat_0_0_fu_162[23:8] <= 16'b0000000000000000;
    pix_mat_0_1_fu_166[23:8] <= 16'b0000000000000000;
    pix_mat_1_0_fu_174[23:8] <= 16'b0000000000000000;
    pix_mat_1_1_fu_178[23:8] <= 16'b0000000000000000;
end



endmodule //lap_filter_axis

